- .eslintrc.json
- package-lock.json
- package.json
- src/app.component.spec.tsx
- src/basic-map.tsx
- src/client.ts
- src/style.css
- src/use-positions.ts
> feat: show subscribed busses location

- README.md
- package-lock.json
- package.json
- src/basic-map.tsx
- src/navigation-bar.component.tsx
- src/style.css
- src/use-positions.ts
> feat: show direction of motion

- src/basic-map.tsx
- src/style.css
Smooth marker movement by simple CSS trick! 
Closes #33
> feat: animate transport marker between movement

- src/the-map.tsx
I have restricted users on maximum zoom which is 19.
Signed-off-by: @zilehuda
> restricted user on maximum zoom

- src/data/vehicles.ts
- src/l10n/en.json
- src/l10n/ro.json
- src/l10n/ru.json
- src/the-map.tsx
- src/use-positions.ts
This is work in progress, the pull request was issued just to invoke the tool that generates a URL that allows one to test a preview version of this build.
Unresolved TODO items related to vehicle attributes in a state variable that makes it possible to:
- determine if the vehicle has an "accessibility" feature or not
- determine the route it is currently mapped to
> feat: show vehicle properties in popup

- src/components/route-select.dialog.tsx
- src/l10n/en.json
> feat: allow multiple route select from dialog

- src/app.component.tsx
- src/app.module.scss
- src/components/navigation-bar.component.tsx
- src/the-map.tsx
> fix: reduce map height to not get under header

- config/env.js
- package-lock.json
- package.json
- public/index.html
- src/index.tsx
- src/react-app-env.d.ts
- src/shared/error-boundary.tsx
> chore: add deploy date/hash in header, disable sentry in dev mode

- package-lock.json
- src/components/routes-stations.component.tsx
> fix(stations): fix `iconAnchor` point

- src/i18n.ts
> feat: fallback to other languages when missing translations

- src/components/route-select.dialog.tsx
> feat: store select multiple routes in local storage

- src/components/routes-positions.component.tsx
1. Changing markers to circles, to improve perception. The arrows will be back when the direction smoothing algorithm and map matching are enabled.
2. The other changes are applied by the auto-formatter.
> Round vehicle marker

- src/components/routes-segments.component.tsx
- src/components/routes-stations.component.tsx
> fix: handle property `id` of `Feature` when is `@id`

- src/the-map.tsx
Switched tile source to Maptiler, small font bug fixed
> Switched to Maptiler

- .gitignore
- src/app.component.tsx
- src/components/hud-buttons.component.tsx
- src/components/hud-buttons.module.scss
> make the round route button bounce on the first visit

- src/components/routes-positions.component.tsx
> show route number in the pop-up

- src/components/routes-positions.component.tsx
- src/l10n/en.json
- src/l10n/ro.json
- src/l10n/ru.json
> check by interval if markers are outdated

- README.md
As we prepare for Hacktoberfest, we need a more convincing "sales pitch" to attract potential contributors. I listed some of the highlights that make our project unique.
Please have a look and suggest ways to make it better.
- What motivated you to contribute?
- What are, in your opinion, the main reasons to support this project?
> Hacktoberfest readme update

- src/app.component.tsx
- src/components/colors-legend.components.tsx
- src/components/colors-legend.module.scss
- src/components/map-control.component.tsx
- src/components/route-select.dialog.tsx
- src/components/routes-positions.component.tsx
- src/components/routes-positions.module.scss
- src/components/routes-segments.component.tsx
- src/index.tsx
- src/route-colors.context.tsx
- src/selected-routes.context.tsx
- src/shared/colors.ts
- src/the-map.tsx
closes #57, with some 'inaccuracies':
1. Random colors instead of hardcoded ones;
2. There's already a route number within a marker;
3. Segments have ultra- slightly lighter color version;
4. 'Do not display more than 4 routes at once' constraints aren't added.
> feat: add multi route colors 🎉

- src/components/routes-positions.component.tsx
> feat: Render vehicles as "off" if within trolleybus parks

- public/index.html
> feat(pwa): add apple-touch-icon link

- src/components/colors-legend.components.tsx
- src/components/colors-legend.module.scss
Close https://github.com/roataway/roataway-web/issues/132
> feat: add collapse button for route labels

- src/components/routes-positions.component.tsx
- src/components/routes-positions.module.scss
> fix: unwanted marker drift on zoom

- src/components/routes-segments.component.tsx
Make the route segment not that thick. Closer to the previous version before https://github.com/roataway/roataway-web/commit/a9b13be6264cc5824801364c1ee88eaddee02767.
> fix: change weight of RoutesSegments

- src/components/routes-positions.component.tsx
- src/shared/rtec-client/subscriptions/event.route.ts
Close #118
Any ideas on how to receive `"remove"` event for proper testing?!!
> feat: vehicle off-route updates
